scrape_configs:
  - job_name: 'snmp'
    static_configs:
      - targets:
        - 88.200.24.238  # SNMP device.
    metrics_path: /snmp
    params:
      module: [vyatta]
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: 192.168.99.100:9116  # SNMP exporter.
        
       